### ISSUE TITLE
MetaGame Shilling School

### ISSUE THREAD

**Issue by yeqbfgxjiq** [MetaFam/MetaGame#10]
# MetaGame Shilling School

She shills seashells at the sea shore, but why? Why does Sally shill? Because, shilling is a lever that multiplies the power of all the other things.

For example: *if a tree falls in a forest and no one hears it, does it matter? If your app is the coolest thing ever, but no one uses it, does it matter?* No! No one cares!

Shillers help people find what you found, they help people care, and most importantly they help people "get it." So... if you get MetaGame and want to help everyone else realize how cool it is, look no further than the **MetaGame Shilling School**. We will teach anyone (even you!) to shill. Soon you'll be shouting from the rooftops and tweeting like a boss with our 12 step program. Let's begin!

## Step 1: Learn about MetaGame

Read everything you find [here](https://metagame.wtf/learn) and remember: The greater the knowledge the better the shill. 

Then post to the [#shill](https://discord.gg/d2tvcQ) channel a single paragraph explaining what MetaGame is and why it's awesome. This paragraph must use your own words! If you use someone else's words we will require you to then complete 2 more tasks to move to the next step. If, however, you use someone else's words and we do not catch you then you are an expert shiller and can jump to step 5. 

## Step 2: Engage with the shilling community

Yes, even shillers have a community! 

Hangout in the #shill channel on [Discord](https://discord.gg/h3BYBQ) to learn the shillosophy of the MetaGame. Engage in discussions and stuff and then move to step 3, if you dare...

## Step 3: Create a dank meme

You know what to do. 

If you have any questions, return to step 2.

## Step 4: Tweet up a storm

Follow the MetaGame [Twitter](https://twitter.com/MetaFam) to shill what we shill. Then package your 5+ favorite things about MetaGame into 120 characters or less and tell the world. Make sure to add a hashtag so that other #MetaGame shillers can find and retweet! Share your tweetstorm to the #shill channel and shill people to shill your shills!  

## Step 5: Repackage and reshill tweets on other platforms

Let's face it, your first few tweetstorms probably suck. That's ok! Just go find tweetstorms that other shillers have shilled and reshare them on other platforms then share your post in the #Shill channel. Redux, reuse, reshill! 

## Step 6: Write something of value

I know the word "value" is viewed suspiciously in the shilling community, but fear not! It doesn't bite. Value can actually increase the impact of your shilling. Let's explore how that works...

First, just start writing. Literally, if you do nothing else do this. Just write. Write a lot. Write until you have what could be viewed as a blog post. Then publish that post to a blog like Medium. Congratulations! You're technically a blogger.

Now, what's the next step? If this was not immediately obvious to you then you might want to reconsider your career as a MetaGame shiller. Fear not, however, as you're still in school and we're here to help. The next step is to shill the thing you just wrote! Of course! Duh.... 

## Step 7: More shilling

When in doubt, shill. Something, anything, just shill it! 

It's always a good time to shill and there's always things to shill. Even as you graduate through the 12 steps of shill mastery you'll always remember your humble beginnings. Always be shilling. 

## Step 8: Shill someone big and important

If you want to make a name for yourself, there's nothing like shilling a whale. Whales are big, and big things are hard to shill. If you can shill a whale, esp one that's lurking deep in the ocean, you win! Winners shill whales and convince them that your ideas are their ideas and those ideas are awesome and you guys are awesome together working on the coolest thing ever: MetaGame.

## Step 9: Get said whale to donate to MetaGame

It's not real until they commit. Getting a whale to blow a spout of tokens into the MetaGame universe is one of the ultimate achievements of a shiller. Note: whales are often hard to find. Lucky for you, whaling season coincides perfectly with the Gitcoin Matching CLR grants! If you don't know what this is, return to step 7 and/or ask someone in the #shill channel.

## Step 10: Mentor new shillers

Congratulations! You've made it to step 10. This is quite an achievement. Consider yourself a navy seal of shilling. Special ops. You can swim the seas of the metaverse, shilling whales and octopi and everything in between. You are a champion.

Not everyone, however, is quite so talented. It takes courage and wisdom to get to where you're at. If you can shill more shillers on how to shill then your shilling impact is multiplying. Considering that shilling already multiplies the efforts fo the MetaGame in general, this is exponential growth! 

## Step 11: Less is more

This one is very counter intuitive, I know... but sometimes the best way to shill is to act like you're not shilling. Not going to explain this one, but when you're ready the way will be made clear.

## Step 12: Write this guide

You're welcome.

**Comment by yeqbfgxjiq** [comment]
And if that's not inspiration enough, just wait til you hear what my fine friend Shillspeare has to say:

> To shill, or not to shill, that is the question:
> Whether 'tis nobler in the mind to suffer
> The slings and arrows of outrageous development,
> Or to take Arms against a Sea of trolls,
> And by opposing end them: to disconnect, to rest;
> No more; and by a rest, to say we end
> The heart-ache, and the thousand natural shocks
> That Twitter is heir to? 'Tis a consummation
> Devoutly to be wished. To disconnect, to rest,
perchance to build; aye, there's the rub,
> For in that rest of disconnection, what buidl may come,
> When we have shuffled off this temporary facade,
> Must give us pause. There's the respect
> That makes Calamity of so long life:
> For who would bear the Whips and Scorns of founding,
> The public's wrong, the arm chair critique's Contumely,
> The pangs of dispised admiration, the regulator’s delay,
> The insolence of bureaucratic token governance, and the spurns
> That patient merit of the unworthy opinions,
> When he himself might his Quietus make
> With self doubt? Who would Fardels bear, [F: these Fardels]
> To grunt and sweat under a diet of ramen and pizza,
> But that the dread of something after disconnection,
> The undiscovered simplicity, from whose bourn
> No traveller returns, puzzles the will,
> And makes us rather bear those ills we have,
> Than fly to others that we know not of.
> Thus fomo does make cowards of us all,
> And thus the native hue of Resolution
> Is sicklied o'er, with the pale cast of Thought,
> And enterprises of great pitch and enthusiasm,
> With this regard their will fumbles,
> And lose the name of Action. Soft you now,
> The fair Ophelia? Nymph, in thy Orisons
> Be all my sins remember'd.

**Comment by yeqbfgxjiq** [comment]
# Note!
The latest version of this brilliant prose is featured on the MetaGame Discourse forum
https://metagame.trydiscourse.com/t/shilling-school/26/2

**Comment by krzysu** [comment]
@burrrata can we close this issue as it is deprecated and even the link in the previous comment is outdated?
