### ISSUE TITLE
MetaGame Contributor Guide

### ISSUE THREAD

**Issue by yeqbfgxjiq** [MetaFam/MetaGame#11]
> Short and sweet version

<br>

# Metagame Contributor Guide

_Changing the game from zero-sum to positive-sum_

## Step 1: learn

Go to https://metagame.wtf/ and click on the Learn button.

Read all the things, esp [this](https://metagame.substack.com/p/how-to-become-a-founder-of-metagame) thing.

## Step 2: play

Find a way to add value.

Don't ask what Metagame needs, ask what makes you excited to contribute!

Then do that thing.

## Step 3: contribute

Once you've learned and done all the things then you can help people with their things. 

Check the [#quests-and-challenges](https://discord.gg/ejD78F) channel in Discord to see if there's anything cool going on.

There's also probably going to be an endless pile of open Issues to triage in the [Metafam GitHub repos](https://github.com/MetaFam/).

<hr>

If you have any questions, please ask! The #general and/or #buidl channels are probably a good place to start, but any question is better than no question. May the force be with you 🐙

**Comment by yeqbfgxjiq** [comment]
> Longer version

<br>

# Metagame Contributor Guide

_Changing the game from zero-sum to positive-sum_

## Step 1: learn

Go to https://metagame.wtf/ and click on the Learn button.

Read all the things, esp [this](https://metagame.substack.com/p/how-to-become-a-founder-of-metagame) thing.

## Step 2: play

Find a way to add value.

Don't ask what Metagame needs, ask what makes you excited to contribute!

Then do that thing.

## Step 3: contribute

Once you've learned and done all the things then you can help people with their things. 

Check the [#quests-and-challenges](https://discord.gg/ejD78F) channel in Discord to see if there's anything cool going on.

There's also probably going to be an endless pile of open Issues to triage in the [Metafam GitHub repos](https://github.com/MetaFam/).

More specifically, all these things would be helpful...

### In General
- [Subscribe](https://metagame.substack.com/publish/post/https://metagame.substack.com/subscribe?) to the MetaGame newsletter.
- [Follow and retweet](https://twitter.com/MetaFam) MetaGame on Twitter.
- Repost and shill MetaGame stuff to all the other places (Reddit, Telegram, etc...)
- Comment "MetaGame made me do it" on completely unrelated things
- Complete the MetaGame quest on Gitcoin (is there a link to this?)
- Hangout in the [MetaGame interspaces](https://interspace.metagame.wtf/) and say some stuff.
- Participate in weekly MetaGame community calls (every Friday at TBD time).
- [Read](https://metagame.wtf/learn/) the rest of the MetaGame articles you probably glossed over.
- Signal your alliance with the MetaFam on Twitter.
- [Join us on Discord](https://discord.gg/bPWZAZ) & claim your Seeds for completing these challenges!

### If you like to build things
- [Work](https://github.com/MetaFam/MetaGame/issues) on the website.
- Work on the character creation form (TBD)
- Work on the player profiles (TBD)
- Work on the card generator (TBD)

### If you like to shill things
- Make a meme about MetaGame
- Write an article about MetaGame
- Make a video about MetaGame
- Bring more players into the MetaGame
- Help onboard new players to help them start shilling too!

### If you like to run things
- Run the MetaGame meetings
- Take notes of said meeting
- Run questions and challenges
- Run the [MetaFam Twitter](https://twitter.com/metafam) (assuming this is taken already)
- Run the [ChievMint Factory](https://twitter.com/mintitpls) on Twitter
- Run the MetaGame Discord 

<hr>

If you have any questions, please ask! The #general and/or #buidl channels are probably a good place to start, but any question is better than no question. May the force be with you 🐙

**Comment by yeqbfgxjiq** [comment]
> Note: [the latest version of this guide](https://hackmd.io/RwArC6n-TL-joS-TS4RmOg?view) may or may not be on HackMD.

**Comment by wkarshat** [comment]
The HackMD link above is to an older version of the Shilling Guide.

Has this guide been superseded now, by a version at another location?
