### ISSUE TITLE
MetaGame Strategy Stuff

### ISSUE THREAD

**Issue by yeqbfgxjiq** [MetaFam/MetaGame#13]
> Just dropping this here until there's a better place for it.

<br>

## Vision

MetaGame is a game to play games. A grassroots initiave led by and for our players. Together we are creating the future.

Throughout history many of us were suppressed due to intrenched interests, regulation, and barriers to entry. This is no more. DAOs enable anyone anywhere to rally together around original ideas. DAOs are (relatively) cheap to setup, manage, and run globally from day 1. MetaGame is an open source innovation engine that brings together all the tools and expertise you need to launch a DAO for your internet native community, project, and/or business.

<br>

## Business / Token Models

MetaGame imagines a universe of guilds (DAOs with a purpose) that are aligned with the MetaGame manifesto. Different types of guilds will produce different types of resources and services. For example, a podcast or media guild would be producing media whos value is derived by the amount of attention people are willing to pay towards that media. A dev shop guild would be producing apps and tools who's value is determined by how many projects or people use their things. Each guild would have it's own token which can be redeemed for the services of that guild. Guilds would offer a portion of their tokens to the MetaGame DAO in order to participate in the MetaGame Universe.

The MetaGame DAO would then use those tokens as collateral to back SEEDs, the meta-token of the MetaGame. SEED holders can then redeem their SEEDs for the MetaGame DAO's underlying collateral or use their tokens to vote on how the MetaGame should operate. In the later case, the MetaGame DAO could vote to buy back SEEDs, sell underlying collateral, or mint more SEEDs. These actions would need to be taken in the spirit of realizing the MetaGame manifesto. For example, all MetaGame SEED holders could vote to mint new SEEDs to give to a new dev team building a new feature for the MetaGame (VR octopi game, obviously). Taking this action would dilute existing SEED holders, but if the new feature created more value than it cost, this could end up being a net win for all parties involved, esp the MetaGame.

There are two ways to get SEEDs:
- contribute tokens to the MetaGame DAO to provide collateral for all SEED holders.
- contribute work to the MetaGame DAO to build the MetaGame infrastructure and community.

<br>

## Show me the money!

While the cryptoeconomic alignment of SEEDs is cute from a theoretical perspective, one does not simply change the game. It's going to require a lot of work. There's only so much time in the day, so we need a way to support and incentivize early contributors with something more tangible than hopes and dreams. This section explores what that might look like.

### Swag
- Everyone likes swag
- Acts as marketing as well as revenue
- Easy to shill
- MetaFactory is laying down the foundations for this

### Personal Tokens & DAOs
- Make it easy for people to create characters (tokens/DAOs) and then attribute reputation, rewards, and badges. 

### 1 Click Guild
- Make it easy for people to launch their own Guild to start participating in the MetaGame.
- This could be a deployment fee for using a prebaked DAO template and/or premium support from the MetaGame fam (weighted by reputation) to start setting things up
- Eventually MetaGame could evolve into a virtual company setup that's low cost, fast, opensource, and global: co-operative, gamification for virtual companies. This would help position DAOs as native internet companies; the next step in better, faster, stronger business setup. This unlocks better business models and value transfer for global consumers and brands, increasing audience and community development. As human interaction across the internet is accelerating you need the right tools for the job. You need MetaGame DAOs.

### In Game Economies
- Premium subscriptions that allow members to access extra goods and services.
- NFTs that grant badges to early contributors as well as a marketplace to create and trade MetaGame NFTs.
- Leaderboards for contributors (time and money) to gamify the game
- Leasing plots for premium placement for ads and things in the MetaGame (shill! shill!)
- Loot boxes with random NFTs, SEEDs, and a bunch of other junk. The cost of these to the MetaGame would be X, but they could be sold for 2 or 3 X.
- Random rewards! Randomly airdrop SEEDs, NFTs, or other fun prizes to players based on reputation. It would be somewhat randomized, but within a normal distribution so that having more SEEDs/reputation will in general get you more random rewards.

### Reputation
- achievement minting as a way to verify work and establish reputation
- in a game where people hire individuals and guilds to do work, having reputation will allow players to earn a higher reward for their contributions
- raid ratings: a rating system and set of analyists who will review raid proposals and determine their potential impact. Then investors could buy SEEDs and pledge them to the raids. In return, investors get a percentage of the loot from raids. This is where the original term "venture captial" came from back in the days of whaling ships and spice runs.   
- Onboarding: incentivize onboarding with progressive reputation and rewards for engagement. Examples might include player setup completed, basic education completion, first contact, guild activity, etc... This incentivizes people to go through the boring hoops of getting setup (esp navigating the terrifying terminology and UX of crypto). It also means that once players are onboarded they will be able to provide more value than someone who simply signs up. This could be incorporated into a reputation system where as you earn more experience points you'll have a higher value for raids and/or when people want to hire you for things.

### Governance
These governance mechanisms require people to buy and use SEEDs more than vanilla voting:
- Futarchy campaigns using SEEDs
- Conviction voting using SEEDs

### Education and Events
- Meet-ups are already happening, but need a more formal structure. MetaGame could really help with this to coordinate and deploy talented amazing people to help make events more interesting and engaging.
- The MetaGame is going to attract a lot of people with skills. They could offer to teach/mentor others in order to earn SEEDs. This has the advantage of attracting talent to the ecosystem as well as developing talent within the ecosystem (thus raising the value of the MetaGame overall). 

<br>

# Next Steps

The above mentioned ideas are just a shmorgishboard of things that were in the Discord channels that I organized and reframed in the context of a rough outline of what one day might be a plan (for something great!). Not sure if these ideas have already been discussed, and if so which should be removed and what's missing that should be added. Overall, just wanted to make sure all the effort and awesomeness that went into the chats didn't get lost in the shuffle. Also wanted to distill the core ideas of the MetaGame into a doc because I like docs.

As always, what do you guys think? Is this more or less in line with what you're thinking? Is this all just craziness and nonsense? Please let me know!

We can then drop the lame stuff and improve upon on the cool stuff :)

**Comment by yeqbfgxjiq** [comment]
This page has moved!
https://metagame.trydiscourse.com/t/metagame-strategy-stuff/28

**Comment by wkarshat** [comment]
https://forum.metagame.wtf/t/metagame-strategy-stuff/28

Close issue?
