### ISSUE TITLE
Players

### ISSUE THREAD

**Issue by yeqbfgxjiq** [MetaFam/MetaGame#14]
### A table of all the players of MetaGame

- Their current rank
- Drop down a few sentences:
  - Why do they want MetaGame to be real
  - What do they want from it
  - What is their role in making it happen
  - What do they usually do
- Links to their twitter, contact info or whatever they want to put on there
- A call to action and link to the application form.

**Comment by Christofon** [comment]
would be down to tackle that. just, what do you mean with the last point?
