### ISSUE TITLE
SEED Entitlement Guide

### ISSUE THREAD

**Issue by yeqbfgxjiq** [MetaFam/MetaGame#18]
_You get some SEEDs! You get some SEEDs! You get some SEEDs!_

<br>

> Note! [The latest version of this guide is here on HackMd](https://hackmd.io/PnLey8tzSduNiLhD0x8mEw?view), but creating a GitHub Issue to create a more permanent embodiment of this priceless relic.

<br>

Did you do cool stuff that makes MetaGame awesome? If so, then you earned SEEDs! Congratulations :)

This doc aims to help you claim all the SEEDs you are rightfully entitled to. That's right, just take a deep breathe and enjoy that pure clean all-natural sense of entitlement. It's yours. You earned it.

The problem is, not everyone knows. There are people who are unaware of how awesome you are (the horrors!). We're going to fix that right away with this MetaGame Entitlement Guide. 

<br>

## Step 1

Shill thyself. 

I shill therefore I am, and this guide is proof of that truth. If you don't shill yourself you won't earn SEEDs, and if you don't earn SEEDs you won't be part of the MetaGame, and if you're not part of the MetaGame then what are you doing with your life??? Seriously, you might want to re-examine your priorities. 

Anyways... Shilling is just shorthand for proof of contributions. If you contributions suck, your shilling will be viewed as spam. If your contributions are awesome, your shilling will be viewed as education. If your contributions are legendary, your shilling will become gospel. 

<br>

## Step 2

Measure and manage!

Your decisions can only be as good as the data they're based on. If you don't know what you've done to contribute, your shilling will not sound as entitled and rightous as it needs to be. Sad. Get your shit together and throw it against the wall to see what sticks. Then you'll know your worth.

### Onboarding Quest

Did you go to the #signpost channel and complete the first quest? If so, you're a winner! If not, go complete the quest dummy.

> +10 SEEDs for the #signpost onboarding quest

### GitHub

Have you contributed to the MetaFam GitHub organization in any way, shape, or form - ever? If so, list it here. Feel free to embelish the truth as no one's going to be not lazy enough to actually check ;)
- Awesome GitHub contribution goes here.
- Super important GitHub related discussion goes here.
- The PR to end all PRs goes here.

Remember, you're worth it!

> How many points per GitHub Issue, comment, or PR? We don't know! Start a conversation in the #seed-claiming channel and suggest a high number.

### Discord

Everyone's earned SEEDs on Discord, they just don't know it yet. Rise above the crowd with this handy dandy guide:
- Did you bring anyone into the Discord chat and/or introduce them to MetaGame? Points!
- Did you share a cool idea that laid the foundation for the culture and history of MetaGame? Points!
- Did you get a bunch of octopi emojis on anything you posted? Points!

Remember, you can always beg for forgiveness, but you miss all the shots you don't take. Shill! Shill! Shill!

> Referals result in 10% of the SEEDs new members make, but good luck tracking that lol

### Twitter

Re-shill your Twitter shills on this form! Maybe you can even double count them. Who knows? Who cares? No one's going to check ¯\\\_(ツ)\_/¯

Bonus points for:
- Shilling something that got re-shilled by prominent peeps.
- Shilling MetaGame in the context of something else that got lots of eyes on the prize.
- Shilling creatively to elevate the art form.

> Tweets are worth a SEED or two each and retweets are worth a SEED. [#cunningham](https://meta.wikimedia.org/wiki/Cunningham's_Law)

### Blogging

It's a thing. People do it. Did you do it? If so, claim those SEEDs!

How many SEEDs are you going to claim? You'd better not say a few! Here's to maximize the shit out of your SEED claims:
- Brainstorm your blog post in the MetaGame Discord chats and/or GitHub Issues. Get people involved. Get those octopi emojis!
- Post a draft. Claim SEEDs for it! 
- Request reviews on the draft and let those people claim SEEDs for their help.
- Post the blog post and claim SEEDs for the blood, sweat, and tears that went into creating such deep and moving writing.
- Shill the shit out of your new blog post and claim SEEDs for all that shilling. Don't forget to mention all the people who re-shilled your shilling! You're the enabler. Own it and reap the benefits.
- Reference said deep and impactful blog post everywhere you can. Then bring it up as a contribution anytime it may or may not be relevant. Claim SEEDs when you do.
- Rinse and repeat until you're the president of the world.

> This is the Konami Code of shilling. Use it wisely. If you have to ask, don't.

### Cold Hard Cash

Did you throw down your hard earned cheddar to support the MetaFam. You're the boss! Write that down here too.

> I forgot how much this is worth, but I don't really care since shilling is like a super power that allows you to print SEEDs.

<br>

### Other Cool Stuff

Did you do anything else awesome? I know you did... Write it down here and request 5-10 SEEDs for it!

Things like casting dots on the manifesto, being on early community calls, and creating memes totally count.

For example Peth.Eth claimed 50 SEEDs for:
- updating the founding sheet, 
- updating the battle plan, 
- setting up roles & permissions, 
- writing the intro quest on Discord, 
- writing the navigation channel post, 
- rewriting the wiki & writing the top half
- editing the new blog post.

Does anyone even know what half of that actually was? Of course not! Doesn't matter. What matters is that we're plowing ahead and planting SEEDs for the future.

> Random cool stuff may or may not count for 0-100 SEEDs. Good luck.

## Step 3

Claim your SEEDs.

Entitlement is just a few clicks away. The next step in your hero's journey is to shill this list of awesomeness to claim your seeds. What are you waiting for!? Just shill it.

<br>

**Comment by yeqbfgxjiq** [comment]
Moved to Discourse: https://metagame.trydiscourse.com/t/seed-entitlement-guide/27

**Comment by wkarshat** [comment]
https://forum.metagame.wtf/t/seed-entitlement-guide/27

Close issue?
