### ISSUE TITLE
Character Creation UX Flow Wireframe ✍️

### ISSUE THREAD

**Issue by META-DREAMER** [MetaFam/MetaGame#2]
Character creation is the first thing you do in any game, so naturally that's the first thing we will be building for MetaGame. We need all the 🧠s to brainstorm and share ideas on what they think the UX flow should be for the character creation process!

Everyone is invited to come up with a sketch / mockup / wireframe for the character creation steps. Here's a list of possible tasks the user will want to accomplish to get you guys started:

- SignIn / SignUp with 3Box Profile
- linking twitter, DAO memberships, gitcoin, ENS, etc (what other things?)
- List off their skills / portfolio
- Enneagram test
- Some level of personalization

What's the most fun and engaging way we can get people to go through this whole process? Here's MetaCartels character creation for inspiration: https://www.metacartel.org/play

**Comment by YalorMewn** [comment]
Just ran through the Meta Cartel character creation process, pretty easy and kind of silly like a throwback to the Zelda days. 

A few things I think we could improve on:
- What are you signing up for here? At what stage is a human/user creating this character profile, can we assume they already have enough information to fill this out? 
- Where does this information end up? How is it displayed? 
- Random stuff to add: Links to Wiki, Demo of existing character card and how it is displayed on the profile, character discovery (where can a new player find other players, maps, what next's, etc) 

Here's some random wild ideas: 
Players start out inside a cocoon, you are viewing the cocoon from outside but it has no features, no definition. It's growing like a giant alien space moth it's becoming whatever it will be. The player lists off skills, experience, and desires and receives points or badges for each section they complete. There can be many badges they receive for different achievements . The badges can help players organize with others who have also completed certain tasks or quests and the beginnings of a guild appear. 

I like the idea of highlighting motivation, allowing the game to group people together by their motivations could be an interesting part of the character creation process. A players motivation could be very specific or very broad thus certain types of information are relevant based on the motivation (*I'm a newbie* = How to get started FAQ's, How to play the game, What this MetaGame is all about) all the way up (*I'm a crypto veteran*= Here's how we fund the MetaGame, This is what MetaGame does to existing marketplaces, KPI's for success, partners or existing guilds, etc) 

The Enneagram test is a great idea, I'm not sure how we narrow the player down to their strongest type though ( the test I did gave me 3 types and they are all equally accurate of my personality) so perhaps it is modular ? more questions to give us greater insights. 

Perhaps as well as linking social profiles, DAO memberships, etc we could also ask users to pick a point on the map that would allow us to create a web of players around the globe and show players where others in their region are already playing the game (think of SnapChat find my friend feature) this could encourage online and offline connections. 

I think the player cards could actually become business cards, imagine if at a certain level of achievement we could just screen shot the players profile and print it and send it off to them to use as their own freelancer cards ! Okay maybe getting crazy far along here. 

Will need to come back with some screens perhaps that will help clarify this for the designers. That's all for now <3

**Comment by peth-eth** [comment]
Here's some inspiration for the profiles, the "designs" I made
https://www.figma.com/file/4AuKEdHQofCud0ve74Jd9W/Untitled?node-id=0%3A1
