### ISSUE TITLE
SEED Claiming Guide

### ISSUE THREAD

**Issue by yeqbfgxjiq** [MetaFam/MetaGame#20]
# Claim Your Seeds!

So you got some SEED's for doing something, well that's GREAT !!!!

First things first, you'll need to check the [Seed Sheet](https://docs.google.com/spreadsheets/d/1lGaIQ0gvfpMVhq-bjOgE2HbnTdS3aN1lO_tdmB9od80/edit#gid=0) to see how many seeds you’ve earned. 

Then you can head on over to the [MetaGame DAO](https://mainnet.aragon.org/#/metagame/0xa8cc7c973e56178f527639fa1661e6f3c29307eb/), open the Tokens app, click `SEED`, click `Add tokens`, then add your Ethereum address and the number of SEEDs you'd like. This will open a vote in the DAO for current SEED holders to read and review. 

> Link to SEED claiming GIF walk through: https://imgur.com/MT19Wdt

Turns out, SEED holders are busy planting for the future. If you want SEED holders to give you SEEDs, give them a good reason to! Go shill yourself. Do it on Discord. Do it on Twitter. Shill here, shill there, shill yourself everywhere. Let everyone know about all your SEEDs that are coming. The more you shill, the more likely you are to produce SEEDs! Shill! Shill! Shill!

> Pro tip: drop into the [MetaGame Discord](https://discord.gg/vYT783B) and shill MetaGame whales like @Hammad, @PEth, and @Yalor 

If your request is legit, you should see your tokens in your wallet in the near future. Haven’t gotten your Seeds yet? We recommend obsessively checking the status of [open votes in the MetaGame DAO](https://mainnet.aragon.org/#/metagame/0xac7567866c25fcc4c547619007362183b5c0ad8d/). 🤪

**Comment by yeqbfgxjiq** [comment]
Dropping this here so that it's easy to reference or extend in the future

**Comment by yeqbfgxjiq** [comment]
The latest and greatest version of this guide is here: https://metagame.trydiscourse.com/t/metagame-seed-claiming-guide/21

**Comment by wkarshat** [comment]
My understanding is that the current link is https://forum.metagame.wtf/t/metagame-seed-claiming-guide/21

Can probably close this issue.
