### ISSUE TITLE
We need MetaGame Scripture/Lore, for fun and facts. 

### ISSUE THREAD

**Issue by YalorMewn** [MetaFam/MetaGame#21]
### MetaGame Genesis Scripture 0x : 
In the beginning **MetaGame** manifested a [notion](https://www.notion.so/metagame/Welcome-0b14ebc7d0b440a58558d8795421b660) of a new [medium](https://medium.com/metagame-perspective). Now the game was formless and empty, darkness was over the surface of the deep, and the Spirit of **Cthulhu** was hovering over the Game. And MetaLord said, "Let there be Value," and there was value. 

**MetaLord** saw that the value was good, and they separated the Value from the Valuable.

**Comment by danforbes** [comment]
Hi, I enjoy writing and would love to help out with this :rocket: What's the best way to get in touch regarding more details about what you have in mind?

**Comment by YalorMewn** [comment]
Hey @danforbes it all goes down on Discord, recommend starting out by diving through all the articles then heading to a Interscope meeting. Bi-weekly on Friday, DM me and I'll add you to the calendar invite !
