### ISSUE TITLE
Setup Aragon DAO to assign seeds

### ISSUE THREAD

**Issue by META-DREAMER** [MetaFam/MetaGame#3]

**Comment by YalorMewn** [comment]
**Move over Mystery Ghost Token:** 
<img width="282" alt="Screen Shot 2020-01-05 at 9 36 05 AM" src="https://user-images.githubusercontent.com/34845103/71785015-d306d500-2f9e-11ea-8ddf-88e6e9c7feaf.png">
**Meta Game Token is here:**
<img width="260" alt="Screen Shot 2020-01-05 at 9 30 07 AM" src="https://user-images.githubusercontent.com/34845103/71785017-d5692f00-2f9e-11ea-82f3-5a9daca62111.png">

**Comment by YalorMewn** [comment]
https://mainnet.aragon.org/#/metagame

**Comment by yeqbfgxjiq** [comment]
This is really cool! Would you guys want to chat sometime about the MetaGame, your goals for the DAO, and if there's anything Aragon can do to help you guys succeed?  

> Full disclosure I'm the [Head of Growth at the Aragon Association](https://blog.aragon.org/aragon-association-team/), but TBH I thought you were using MetaCartel until I saw this Issue lol

**Comment by yeqbfgxjiq** [comment]
[We are assigning SEEDs](https://metagame.substack.com/p/metagame-goes-on-made-seeds-claim). Mission accomplished and high-fives all around!
- Plus many to @pythonpete32 and @0xgabi for their help

@YalorMewn we're good to close this out right?
