### ISSUE TITLE
Username Error

### ISSUE THREAD

**Issue by jsusim** [MetaFam/MetaGame#39]
![image](https://user-images.githubusercontent.com/60559400/115835404-cedb2100-a448-11eb-82c9-d3680eae4b2e.png)

No special characters involved but there is still an error occurring.

**Comment by dysbulic** [comment]
This repository is no longer used. The source issue is uppercase letters are not allowed. A [pull request](https://github.com/MetaFam/TheGame/pull/474) to correct the message has been submitted to the active repository.
