### ISSUE TITLE
Setup Landing Page

### ISSUE THREAD

**Issue by META-DREAMER** [MetaFam/MetaGame#4]
Links to public notion page for "manifesto"

**Comment by geleeroyale** [comment]
Heya - How far are you guys with development? Gatsby is my favorite stack and would love to help build any websites that are worked on. Can do design, but prefer to do implementation.

**Comment by META-DREAMER** [comment]
@geleeroyale Just got the landing page setup. Going to be implementing the character creation and profiles at ETHDenver. Are you going to be there by any chance?
