### ISSUE TITLE
Assemble the MetaGame Manifesto

### ISSUE THREAD

**Issue by META-DREAMER** [MetaFam/MetaGame#5]
Organize thoughts, ideas, writing, and battle plans from the Notion into an approachable structure for newcomers to understand what MetaGame is and give us a holistic overview of the things we are trying to achieve

**Comment by YalorMewn** [comment]
[WIP](https://docs.google.com/document/d/1yNzF7-FrHuHAnS4YZhDcMa4lFiyZNCDZ0tImWe0SbuA/edit?usp=sharing)

**Comment by YalorMewn** [comment]
Check it out fam......https://github.com/YalorMewn/MetaGame/wiki/Manifesto

**Comment by wkarshat** [comment]
Is Github WiKi the right place for working on a Manifesto?

Overlaps #13?

**Comment by YalorMewn** [comment]
We have been dragging our feet on this one because of so many other balls in the air, there is a room on Discord though https://discord.gg/R45Kyy talk to @sepu85 as he was leading it.

**Comment by sepu85** [comment]
> We have been dragging our feet on this one because of so many other balls in the air, there is a room on Discord though https://discord.gg/R45Kyy talk to @sepu85 as he was leading it.

Please have a look at [this PR](
https://github.com/MetaFam/Manifesto/pull/2#issuecomment-596072664)

**Comment by drllau** [comment]
1. Tidied up some headings to be more explanatory
1. Minor wordsmithing plus a few pictures (eg web 3.0)
1. Added some book references to each of the [sections](https://docs.google.com/document/d/13FZC9TtnEW6HZqSbuK3B8mLsdpwzhiGusVJLD9KL7iA/edit#)
Interlude: Crisis Cascade
Satyajit Das (2011) Extreme Money: Masters of the Universe and the Cult of Risk [0-132-79019-X]
Brave New World
Dick & Ruth Foth (2017) Known: Finding Deep Friendships in a Shallow World [0-735-28975-1]
Web of Opportunity
Thomas Friedman (2007) The World is Flat: Further Updated & Expanded 3rd ed. [0-374-29278-7]
Web of Life
Charles Eisenstein (2011) Sacred Economics: Money, Gift and Society in the Age of Transition [1-583-94398-6]
Feedback Loops & Gamification
James Surowiecki (2005) The Wisdom of Crowds:Why the Many Are Smarter Than the Few and How Collective Wisdom Shapes Business, Economies, Societies and Nations [0-307-27505-1]
Fostering Autonomy and Mastery & the culture of challenge
Dan Pink (2011) Drive; The Surprising Truth About What Motivates Us [1-101-52438-3]
Disconnect in the Digital Realm
Johann Hari (2018) Lost Connections: Uncovering the Real Causes of Depression [1-408-87870-4]
MetaWorldview: Stepping outside the rat race
Mike Berners-Lee (2019) There Is No Planet B: A Handbook for the Make or Break Years [1-108-33594-2]
MetaFam: A new digital collective
Safi Bahcall (2019) Loonshots: How to Nurture the Crazy Ideas That Win Wars, Cure Diseases, and Transform Industries [1-250-18597-1]
Why now?
Nicholas Carr (2008) The Big Switch: Rewiring the World, from Edison to Google [0-393-06228-7]
Closing: Investing in Your Future
Alan Kay (1984) Inventing the Future, in The AI Business: The Commercial Uses of Artificial Intelligence ed Patrick Winston & Karen Prendergast [978-0-26-223117-6]
