### ISSUE TITLE
Gather list of resources for "awesome web3"

### ISSUE THREAD

**Issue by META-DREAMER** [MetaFam/MetaGame#6]
Example of an "awesome list": https://github.com/sindresorhus/awesome

Find the best tooling, resources, dapps, podcasts, or anything else in the web3 ecosystem. Can use this list as a basis of what to show people when they go through the "choose your adventure" questionnaire.

**Comment by YalorMewn** [comment]
Starting point for the list [Add To Me](https://docs.google.com/document/d/1u8qeobwSqQR9J8LI0ZGrBAstHi3y5I4sjcXk3hRnMGk/edit?usp=sharing) 🥳

**Comment by yeqbfgxjiq** [comment]
Does this help?

https://github.com/vinsgo/awesome-ethereum

https://www.reddit.com/r/ethdev/comments/9jw839/long_list_of_ethereum_developer_tools_frameworks/

https://github.com/ConsenSys/ethereum-developer-tools-list/blob/master/README.md

**Comment by wkarshat** [comment]
Could be a (series of) Quest?

**Comment by Vanilladelphia** [comment]
As far as Dapps go, here are 2 pretty comprehensive lists.

https://defipulse.com/defi-list
https://dap.ps/

This link has a few more, as well as plenty of other fun things about crypto in general. 
http://www.coinresources.io./
