### ISSUE TITLE
Add SEED token to the Aragon DAO

### ISSUE THREAD

**Issue by YalorMewn** [MetaFam/MetaGame#8]

**Comment by yeqbfgxjiq** [comment]
https://mainnet.aragon.org/#/metagame/0xa8cc7c973e56178f527639fa1661e6f3c29307eb/

Major props to @0xgabi and @pythonpete32 for help making this happen

**Comment by yeqbfgxjiq** [comment]
> Note: you still need to configure [the permissions on the SEED token](https://mainnet.aragon.org/#/metagame/permissions/app/0xa8cc7c973e56178f527639fa1661e6f3c29307eb) so that it interacts with the other contracts/apps in the DAO the way you want it to, but the token has been added to the DAO.

**Comment by YalorMewn** [comment]
Will circle back to setup permission before we make the big push to claim token, thank you for your amazing work @burrrata sensei 🥋 and  #Aragon friends 👾

**Comment by wkarshat** [comment]
Completed, close issue?
